
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','01',707000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','02',707000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','03',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','05',1672141,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','06',1662909.39,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','09',394148.11,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','10',518108.23,getdate(),'USER1',getdate(),'USER1'		
		
		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','13',2255329.11,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','14',1438903,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','15',440849,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','16',7000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','17',274285.11,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','18',94292,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','19',81600,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','20',81600,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','21',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','22',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','23',2773289.11,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','24',2888017.62,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','25',2336929.11,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','27',551088.51,getdate(),'USER1',getdate(),'USER1'		

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','01',551088.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','03',4165,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','09',555253.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','07',4165,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','10',4165,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','14',551088.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','15',193950,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','16',357138.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','17',555253.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','18',555253.51,getdate(),'USER1',getdate(),'USER1'	

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','01',698000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','03',1871909.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','05',1438903,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','06',7000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','07',402586,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','08',294292,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','09',2569909.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','10',2142781,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','12',427128.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','13',2569909.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','14',2569909.39,getdate(),'USER1',getdate(),'USER1'	

/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','01',-427128.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','02',200000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','03',200000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','07',-427128.39,getdate(),'USER1',getdate(),'USER1'	

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','01',427128.39,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','02',518108.23,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','04',945236.62,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','06',311563,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','07',82585.11,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','10',394148.11,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','12',551088.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'	


/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','01',-551088.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','03',-551088.51,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','04',784499.49,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','05',1743,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','06',782756.49,getdate(),'USER1',getdate(),'USER1'	
