
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','01',474500,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','02',474500,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','03',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','04',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','05',637989.39,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','06',744304.53,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','09',608326,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','10',745162.11,getdate(),'USER1',getdate(),'USER1'			
			
			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','13',1213609,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','14',939383,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','15',208326,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','16',6000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','17',900,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','18',59000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','19',31000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','20',20000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','21',9000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','22',2000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','23',1720815.39,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','24',1963966.64,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','25',1244609,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','27',719357.64,getdate(),'USER1',getdate(),'USER1'			

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','01',719357.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','03',26260,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','09',745617.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','07',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','10',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','14',745617.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','15',113753.8,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','16',631863.84,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','17',745617.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','18',745617.64,getdate(),'USER1',getdate(),'USER1'		

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','01',467995.17,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','02',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','03',980214.8,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','05',959383,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','06',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','07',9900,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','08',277386.15,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','09',1448209.97,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','10',1246669.15,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','12',201540.82,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','13',1448209.97,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','14',1448209.97,getdate(),'USER1',getdate(),'USER1'		

/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','01',-201540.82,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','02',229405.44,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','03',216386.15,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','06',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','07',-188521.53,getdate(),'USER1',getdate(),'USER1'		

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','01',188521.53,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','02',745162.11,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','04',933683.64,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','06',208326,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','07',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','10',208326,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','12',725357.64,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'			

/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','01',-725357.64,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','02',20260,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','03',-745617.64,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','04',1320607.15,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','05',151814.85,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','06',1168792.3,getdate(),'USER1',getdate(),'USER1'			
