
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','01',950000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','02',950000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','03',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','04',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','05',1395620,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','06',1395620,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','09',1630000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','10',1630000,getdate(),'USER1',getdate(),'USER1'			
			
			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','13',3786640,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','14',1706640,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','15',145000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','16',25000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','17',1570000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','18',340000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','19',78980,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','20',7980,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','21',71000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','22',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','23',3975620,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','24',3975620,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','25',3865620,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'ABP','27',110000,getdate(),'USER1',getdate(),'USER1'			

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','01',110000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','03',80000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','09',190000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','07',80000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','10',80000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','12',11000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','14',110000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','15',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','16',121000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','17',190000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'EFP','18',190000,getdate(),'USER1',getdate(),'USER1'		

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','01',950000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','02',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','03',1725620,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','05',1839620,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','06',25000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','07',141000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','08',520000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','09',2675620,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','10',2525620,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','12',150000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','13',2675620,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CRP','14',2675620,getdate(),'USER1',getdate(),'USER1'		

/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','01',-150000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','02',330000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','03',180000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','06',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'CAFP','07',0,getdate(),'USER1',getdate(),'USER1'		

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','01',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','02',1630000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','04',1630000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','06',20000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','07',1500000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','10',1520000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','12',110000,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'			
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'			

/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','01',-110000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','02',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','03',-110000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','04',227137.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','05',-278131.94,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2023,'A',0,'SPP2','06',505269.58,getdate(),'USER1',getdate(),'USER1'		
