
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','01',691017,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','02',691017,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','03',25000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','04',25000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','05',1467884,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','06',1467884,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','09',1152376,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','10',1152376,getdate(),'USER1',getdate(),'USER1'


insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','13',2814777,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','14',1614026,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','15',872376,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','16',6500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','17',137375,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','18',184500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','19',42900,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','20',27500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','21',7500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','22',7900,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','23',3311277,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','24',3311277,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','25',2857677,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','27',453600,getdate(),'USER1',getdate(),'USER1'

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','01',453600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','02',5600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','03',22991,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','09',482191,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','06',5600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','07',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','10',5600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','14',476591,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','15',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','16',476591,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','17',482191,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','18',482191,getdate(),'USER1',getdate(),'USER1'

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','01',691017,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','02',25000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','03',2517884,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','05',1641526,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','06',6500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','07',144875,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','08',1242400,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','09',3208901,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','10',3035301,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','12',173600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','13',3208901,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','14',3208901,getdate(),'USER1',getdate(),'USER1'


/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','01',-173600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','02',1050000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','03',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','06',1050000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','07',-173600,getdate(),'USER1',getdate(),'USER1'

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','01',173600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','02',1152376,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','04',1331576,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','06',872376,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','07',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','10',877976,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','12',453600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','13',5600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','14',5600,getdate(),'USER1',getdate(),'USER1'


/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','01',-453600,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','02',-22991,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','03',-476591,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','04',1929182,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','05',-8176,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','06',1937358,getdate(),'USER1',getdate(),'USER1'
