
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','01',9363663,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','02',9363663,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','03',336043,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','04',336043,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','05',3610416,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','06',3835248,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','09',3620000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','10',2923500,getdate(),'USER1',getdate(),'USER1'	
	
	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','13',11594391,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','14',11058891,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','15',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','16',28000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','17',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','18',507500,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','19',2632449,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','20',1533433,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','21',105000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','22',994016,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','23',16594079,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','24',16122411,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','25',14226840,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','27',1895571,getdate(),'USER1',getdate(),'USER1'	

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','01',1895571,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','03',10000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','09',1905571,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','07',10000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','10',10000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','14',1895571,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','15',1781680,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','16',113891,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','17',1905571,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','18',1905571,getdate(),'USER1',getdate(),'USER1'	

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','01',9363663,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','02',336043,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','03',5924603,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','05',11058891,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','06',28000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','07',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','08',3350536,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','09',15288266,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','10',14437427,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','12',850839,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','13',15288266,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','14',15288266,getdate(),'USER1',getdate(),'USER1'	


/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','01',-850839,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','02',2089355,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','03',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','06',1744020,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','07',-505504,getdate(),'USER1',getdate(),'USER1'

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','01',505504,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','02',2923500,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','04',3429004,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','06',1533433,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','07',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','10',1533433,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','12',1895571,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'


/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','01',-1895571,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','02',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','03',-1895571,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','04',5066100,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','05',-173866,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','06',5239966,getdate(),'USER1',getdate(),'USER1'
