
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','01',442000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','02',442000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','03',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','04',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','05',602100.4,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','06',719083.64,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','09',683326,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','10',716534.92,getdate(),'USER1',getdate(),'USER1'		
		
		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','13',1138161,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','14',851335,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','15',208326,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','16',1500,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','17',9000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','18',68000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','19',20932.8,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','20',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','21',19932.8,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','22',1000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','23',1727426.4,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','24',1877618.56,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','25',1159093.8,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'ABP','27',718524.76,getdate(),'USER1',getdate(),'USER1'		

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','01',718524.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','03',12000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','09',730524.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','07',12000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','10',12000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','14',718524.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','15',83332.6,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','16',635192.16,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','17',730524.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'EFP','18',730524.76,getdate(),'USER1',getdate(),'USER1'	

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','01',435962.06,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','03',971106.09,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','05',851335,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','06',1500,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','07',28932.8,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','08',302258.89,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','09',1407068.15,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','10',1184026.69,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','12',223041.46,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','13',1407068.15,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CRP','14',1407068.15,getdate(),'USER1',getdate(),'USER1'	


/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','01',-223041.46,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','02',245984.51,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','03',233258.89,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','06',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'CAFP','07',-210315.84,getdate(),'USER1',getdate(),'USER1'

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','01',210315.84,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','02',716534.92,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','04',926850.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','06',208326,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','07',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','10',208326,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','12',718524.76,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'	


/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','01',-718524.76,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','02',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','03',-718524.76,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','04',1599590.77,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','05',-28362.28,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',1,'SPP2','06',1627953.05,getdate(),'USER1',getdate(),'USER1'
