
/* ABP*/ 
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','01',12990500,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','02',12990500,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','03',80500,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','04',80500,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','05',26320831.14,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','06',26347334.14,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','07',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','08',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','09',14480876,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','10',13690123,getdate(),'USER1',getdate(),'USER1'		
		
		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','13',48585841.41,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','14',20997134,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','15',12668000,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','16',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','17',257501,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','18',14663206.41,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','19',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','20',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','21',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','22',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','23',53792207.14,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','24',53027957.14,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','25',48585841.41,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','26',0,getdate(),'USER1',getdate(),'USER1'		
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'ABP','27',4442115.73,getdate(),'USER1',getdate(),'USER1'		

/* EFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','01',4442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','02',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','03',3000000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','09',7442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','07',3000000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','10',3000000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','12',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','14',4442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','15',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','16',4442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','17',7442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'EFP','18',7442115.73,getdate(),'USER1',getdate(),'USER1'	

/* CRP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','01',12990500,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','02',80500,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','03',34332655.14,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','04',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','05',20997134,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','06',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','07',3254501,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','08',20863206.41,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','09',47323155.14,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','10',45114841.41,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','12',2208313.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','13',47323155.14,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CRP','14',47323155.14,getdate(),'USER1',getdate(),'USER1'	


/* CAFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','01',-2208313.73,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','02',7985320.7,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','03',6900000,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','04',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','05',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','06',0,getdate(),'USER1',getdate(),'USER1'
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'CAFP','07',-1122993.03,getdate(),'USER1',getdate(),'USER1'

/* TFP */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','01',1122993.03,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','02',13690123,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','03',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','04',14813116.03,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','05',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','06',9668000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','07',703000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','08',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','09',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','10',10371000,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','11',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','12',4442116.03,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','13',0,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'TFP','14',0,getdate(),'USER1',getdate(),'USER1'	


/* SPP2 */
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','01',-4442116.03,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','02',-0.3,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','03',-4442115.73,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','04',9598538.79,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','05',352281.57,getdate(),'USER1',getdate(),'USER1'	
insert into GbcpDematBIBR(num_exec,code_budg,no_mvt,type_lib,code_lib,montant,date_crea,aut_crea,date_maj,aut_maj) select 2021,'A',0,'SPP2','06',9246257.22,getdate(),'USER1',getdate(),'USER1'	
